<?php

return array(
    array(
        'name' => 'Afghanistan',
        'code' => 'AF',
        'phone_code' => '+93',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/af.svg',
        'locale' => 'fa_AF',
    ),
    array(
        'name' => 'Albania',
        'code' => 'AL',
        'phone_code' => '+355',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/al.svg',
        'locale' => 'sq_AL',
    ),
    array(
        'name' => 'Algeria',
        'code' => 'DZ',
        'phone_code' => '+213',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/dz.svg',
        'locale' => 'ar_DZ',
    ),
    array(
        'name' => 'American Samoa',
        'code' => 'AS',
        'phone_code' => '+1',
        'phoneLength' =>
            array(
                5,
                6,
                7
            ),
        'flag' => 'assets/admin/img/flags/as.svg',
        'locale' => 'en_AS',
    ),
    array(
        'name' => 'Andorra',
        'code' => 'AD',
        'phone_code' => '+376',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/ad.svg',
        'locale' => 'ca_AD',
    ),
    array(
        'name' => 'Angola',
        'code' => 'AO',
        'phone_code' => '+244',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ao.svg',
        'locale' => 'pt_AO',
    ),
    array(
        'name' => 'Anguilla',
        'code' => 'AI',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ai.svg',
        'locale' => 'en_AI',
    ),
    array(
        'name' => 'Antigua',
        'code' => 'AG',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ag.svg',
        'locale' => 'en_AG',
    ),
    array(
        'name' => 'Argentina',
        'code' => 'AR',
        'phone_code' => '+54',
        'phoneLength' =>
            array(
                6,
                7,
                8
            ),
        'flag' => 'assets/admin/img/flags/ar.svg',
        'locale' => 'es_AR',
    ),
    array(
        'name' => 'Armenia',
        'code' => 'AM',
        'phone_code' => '+374',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/am.svg',
        'locale' => 'hy_AM',
    ),
    array(
        'name' => 'Aruba',
        'code' => 'AW',
        'phone_code' => '+297',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/aw.svg',
        'locale' => 'nl_AW',
    ),
    array(
        'name' => 'Australia',
        'code' => 'AU',
        'phone_code' => '+61',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/au.svg',
        'locale' => 'en_AU',
    ),
    array(
        'name' => 'Austria',
        'code' => 'AI',
        'phone_code' => '+43',
        'phoneLength' =>
            array(
                10,
                11
            ),
        'flag' => 'assets/admin/img/flags/ai.svg',
        'locale' => 'de_AT',
    ),
    array(
        'name' => 'Azerbaijan',
        'code' => 'AZ',
        'phone_code' => '+994',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/az.svg',
        'locale' => 'az_AZ',
    ),
    array(
        'name' => 'Bahrain',
        'code' => 'BH',
        'phone_code' => '+973',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bh.svg',
        'locale' => 'ar_BH',
    ),
    array(
        'name' => 'Bangladesh',
        'code' => 'BD',
        'phone_code' => '+880',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/bd.svg',
        'locale' => 'bn_BD',
    ),
    array(
        'name' => 'Barbados',
        'code' => 'BB',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/bb.svg',
        'locale' => 'en_BB',
    ),
    array(
        'name' => 'Belarus',
        'code' => 'BY',
        'phone_code' => '+375',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/by.svg',
        'locale' => 'be_BY',
    ),
    array(
        'name' => 'Belgium',
        'code' => 'BE',
        'phone_code' => '+32',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/be.svg',
        'locale' => 'fr_BE',
    ),
    array(
        'name' => 'Belize',
        'code' => 'BZ',
        'phone_code' => '+501',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/bz.svg',
        'locale' => 'en_BZ',
    ),
    array(
        'name' => 'Benin',
        'code' => 'BJ',
        'phone_code' => '+229',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bj.svg',
        'locale' => 'fr_BJ',
    ),
    array(
        'name' => 'Bermuda',
        'code' => 'BM',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/bm.svg',
        'locale' => 'en_BM',
    ),
    array(
        'name' => 'Bhutan',
        'code' => 'BT',
        'phone_code' => '+975',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bt.svg',
        'locale' => 'dz_BT',
    ),
    array(
        'name' => 'Bolivia',
        'code' => 'BO',
        'phone_code' => '+591',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bo.svg',
        'locale' => 'es_BO',
    ),
    array(
        'name' => 'Bosnia & Herzegovina',
        'code' => 'BA',
        'phone_code' => '+387',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ba.svg',
        'locale' => 'bs_BA',
    ),
    array(
        'name' => 'Botswana',
        'code' => 'BW',
        'phone_code' => '+267',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bw.svg',
        'locale' => 'en_BW',
    ),
    array(
        'name' => 'Brazil',
        'code' => 'BR',
        'phone_code' => '+55',
        'phoneLength' => '11',
        'flag' => 'assets/admin/img/flags/br.svg',
        'locale' => 'pt_BR',
    ),
    array(
        'name' => 'British Indian Ocean',
        'code' => 'IO',
        'phone_code' => '+246',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/io.svg',
        'locale' => 'en_IO',
    ),
    array(
        'name' => 'British Virgin Islands',
        'code' => 'VG',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/vg.svg',
        'locale' => 'en_VG',
    ),
    array(
        'name' => 'Brunei',
        'code' => 'BN',
        'phone_code' => '+673',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/bn.svg',
        'locale' => 'ms_BN',
    ),
    array(
        'name' => 'Bulgaria',
        'code' => 'BG',
        'phone_code' => '+359',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/bg.svg',
        'locale' => 'bg_BG',
    ),
    array(
        'name' => 'Burkina Faso',
        'code' => 'BF',
        'phone_code' => '+226',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bf.svg',
        'locale' => 'fr_BF',
    ),
    array(
        'name' => 'Burma Myanmar',
        'code' => 'MM',
        'phone_code' => '+95',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mm.svg',
        'locale' => 'my_MM',
    ),
    array(
        'name' => 'Burundi',
        'code' => 'BI',
        'phone_code' => '+257',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/bi.svg',
        'locale' => 'fr_BI',
    ),
    array(
        'name' => 'Cambodia',
        'code' => 'KH',
        'phone_code' => '+855',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/kh.svg',
        'locale' => 'km_KH',
    ),
    array(
        'name' => 'Cameroon',
        'code' => 'CM',
        'phone_code' => '+237',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/cm.svg',
        'locale' => 'fr_CM',
    ),
    array(
        'name' => 'Canada',
        'code' => 'CA',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ca.svg',
        'locale' => 'en_CA',
    ),
    array(
        'name' => 'Cape Verde',
        'code' => 'CV',
        'phone_code' => '+238',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/cv.svg',
        'locale' => 'pt_CV',
    ),
    array(
        'name' => 'Cayman Islands',
        'code' => 'KY',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ky.svg',
        'locale' => 'en_KY',
    ),
    array(
        'name' => 'Central African Republic',
        'code' => 'CF',
        'phone_code' => '+236',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/cf.svg',
        'locale' => 'fr_CF',
    ),
    array(
        'name' => 'Chad',
        'code' => 'ID',
        'phone_code' => '+235',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/id.svg',
        'locale' => 'fr_TD',
    ),
    array(
        'name' => 'Chile',
        'code' => 'CL',
        'phone_code' => '+56',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/cl.svg',
        'locale' => 'es_CL',
    ),
    array(
        'name' => 'China',
        'code' => 'CN',
        'phone_code' => '+86',
        'phoneLength' => '11',
        'flag' => 'assets/admin/img/flags/cn.svg',
        'locale' => 'zh_CN',
    ),
    array(
        'name' => 'Colombia',
        'code' => 'CO',
        'phone_code' => '+57',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/co.svg',
        'locale' => 'es_CO',
    ),
    array(
        'name' => 'Comoros',
        'code' => 'KM',
        'phone_code' => '+269',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/km.svg',
        'locale' => 'ar_KM',
    ),
    array(
        'name' => 'Cook Islands',
        'code' => 'CK',
        'phone_code' => '+682',
        'phoneLength' => '5',
        'flag' => 'assets/admin/img/flags/ck.svg',
        'locale' => 'en_CK',
    ),
    array(
        'name' => 'Costa Rica',
        'code' => 'CR',
        'phone_code' => '+506',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/cr.svg',
        'locale' => 'es_CR',
    ),
    array(
        'name' => 'Croatia',
        'code' => 'HR',
        'phone_code' => '+385',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/hr.svg',
        'locale' => 'hr_HR',
    ),
    array(
        'name' => 'Cuba',
        'code' => 'CU',
        'phone_code' => '+53',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/cu.svg',
        'locale' => 'es_CU',
    ),
    array(
        'name' => 'Cyprus',
        'code' => 'CY',
        'phone_code' => '+357',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/cy.svg',
        'locale' => 'el_CY',
    ),
    array(
        'name' => 'Czech Republic',
        'code' => 'CZ',
        'phone_code' => '+420',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/cz.svg',
        'locale' => 'cs_CZ',
    ),
    array(
        'name' => 'Republic of Congo',
        'code' => 'CD',
        'phone_code' => '+243',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/cd.svg',
        'locale' => 'fr_CG',
    ),
    array(
        'name' => 'Denmark',
        'code' => 'DK',
        'phone_code' => '+45',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/dk.svg',
        'locale' => 'da_DK',
    ),
    array(
        'name' => 'Djibouti',
        'code' => 'DJ',
        'phone_code' => '+253',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/dj.svg',
        'locale' => 'fr_DJ',
    ),
    array(
        'name' => 'Dominica',
        'code' => 'DM',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/dm.svg',
        'locale' => 'en_DM',
    ),
    array(
        'name' => 'Dominican Republic',
        'code' => 'DO',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/do.svg',
        'locale' => 'es_DO',
    ),
    array(
        'name' => 'Ecuador',
        'code' => 'EC',
        'phone_code' => '+593',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ec.svg',
        'locale' => 'es_EC',
    ),
    array(
        'name' => 'Egypt',
        'code' => 'EG',
        'phone_code' => '+20',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/eg.svg',
        'locale' => 'ar_EG',
    ),
    array(
        'name' => 'El Salvador',
        'code' => 'SV',
        'phone_code' => '+503',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/sv.svg',
        'locale' => 'es_SV',
    ),
    array(
        'name' => 'Equatorial Guinea',
        'code' => 'GQ',
        'phone_code' => '+240',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/gq.svg',
        'locale' => 'es_GQ',
    ),
    array(
        'name' => 'Eritrea',
        'code' => 'ER',
        'phone_code' => '+291',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/er.svg',
        'locale' => 'ti_ER',
    ),
    array(
        'name' => 'Estonia',
        'code' => 'EE',
        'phone_code' => '+372',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ee.svg',
        'locale' => 'et_EE',
    ),
    array(
        'name' => 'Ethiopia',
        'code' => 'ET',
        'phone_code' => '+251',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/et.svg',
        'locale' => 'am_ET',
    ),
    array(
        'name' => 'Falkland Islands',
        'code' => 'FK',
        'phone_code' => '+500',
        'phoneLength' => '5',
        'flag' => 'assets/admin/img/flags/fk.svg',
        'locale' => 'en_FK',
    ),
    array(
        'name' => 'Faroe Islands',
        'code' => 'FO',
        'phone_code' => '+298',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/fo.svg',
        'locale' => 'fo_FO',
    ),
    array(
        'name' => 'Federated Micronesia',
        'code' => 'FM',
        'phone_code' => '+691',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/fm.svg',
        'locale' => 'en_FM',
    ),
    array(
        'name' => 'Fiji',
        'code' => 'FJ',
        'phone_code' => '+679',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/fj.svg',
        'locale' => 'en_FJ',
    ),
    array(
        'name' => 'Finland',
        'code' => 'FI',
        'phone_code' => '+358',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/fi.svg',
        'locale' => 'fi_FI',
    ),
    array(
        'name' => 'France',
        'code' => 'FR',
        'phone_code' => '+33',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/fr.svg',
        'locale' => 'fr_FR',
    ),
    array(
        'name' => 'French Guiana',
        'code' => 'GF',
        'phone_code' => '+594',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/gf.svg',
        'locale' => 'fr_GF',
    ),
    array(
        'name' => 'French Polynesia',
        'code' => 'PF',
        'phone_code' => '+689',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/pf.svg',
        'locale' => 'fr_PF',
    ),
    array(
        'name' => 'Gabon',
        'code' => 'GA',
        'phone_code' => '+241',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/ga.svg',
        'locale' => 'fr_GA',
    ),
    array(
        'name' => 'Georgia',
        'code' => 'GE',
        'phone_code' => '+995',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ge.svg',
        'locale' => 'ka_GE',
    ),
    array(
        'name' => 'Germany',
        'code' => 'DE',
        'phone_code' => '+49',
        'phoneLength' => '11',
        'flag' => 'assets/admin/img/flags/de.svg',
        'locale' => 'de_DE',
    ),
    array(
        'name' => 'Ghana',
        'code' => 'GH',
        'phone_code' => '+233',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/gh.svg',
        'locale' => 'en_GH',
    ),
    array(
        'name' => 'Gibraltar',
        'code' => 'GI',
        'phone_code' => '+350',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/gi.svg',
        'locale' => 'en_GI',
    ),
    array(
        'name' => 'Greece',
        'code' => 'GR',
        'phone_code' => '+30',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/gr.svg',
        'locale' => 'el_GR',
    ),
    array(
        'name' => 'Greenland',
        'code' => 'GL',
        'phone_code' => '+299',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/gl.svg',
        'locale' => 'kl_GL',
    ),
    array(
        'name' => 'Grenada',
        'code' => 'GD',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/gd.svg',
        'locale' => 'en_GD',
    ),
    array(
        'name' => 'Guadeloupe',
        'code' => 'GP',
        'phone_code' => '+590',
        'phoneLength' => '12',
        'flag' => 'assets/admin/img/flags/gp.svg',
        'locale' => 'fr_GP',
    ),
    array(
        'name' => 'Guam',
        'code' => 'GU',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/gu.svg',
        'locale' => 'en_GU',
    ),
    array(
        'name' => 'Guatemala',
        'code' => 'GT',
        'phone_code' => '+502',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/gt.svg',
        'locale' => 'es_GT',
    ),
    array(
        'name' => 'Guinea',
        'code' => 'GN',
        'phone_code' => '+224',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/gn.svg',
        'locale' => 'fr_GN',
    ),
    array(
        'name' => 'Guinea-Bissau',
        'code' => 'GW',
        'phone_code' => '+245',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/gw.svg',
        'locale' => 'pt_GW',
    ),
    array(
        'name' => 'Guyana',
        'code' => 'GY',
        'phone_code' => '+592',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/gy.svg',
        'locale' => 'en_GY',
    ),
    array(
        'name' => 'Haiti',
        'code' => 'HT',
        'phone_code' => '+509',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ht.svg',
        'locale' => 'fr_HT',
    ),
    array(
        'name' => 'Honduras',
        'code' => 'HN',
        'phone_code' => '+504',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/hn.svg',
        'locale' => 'es_HN',
    ),
    array(
        'name' => 'Hong Kong',
        'code' => 'HK',
        'phone_code' => '+852',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/hk.svg',
        'locale' => 'zh_HK',
    ),
    array(
        'name' => 'Hungary',
        'code' => 'HU',
        'phone_code' => '+36',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/hu.svg',
        'locale' => 'hu_HU',
    ),
    array(
        'name' => 'Iceland',
        'code' => 'IS',
        'phone_code' => '+354',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/is.svg',
        'locale' => 'is_IS',
    ),
    array(
        'name' => 'India',
        'code' => 'IN',
        'phone_code' => '+91',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/in.svg',
        'locale' => 'hi_IN',
    ),
    array(
        'name' => 'Indonesia',
        'code' => 'ID',
        'phone_code' => '+62',
        'phoneLength' => '11',
        'flag' => 'assets/admin/img/flags/id.svg',
        'locale' => 'id_ID',
    ),
    array(
        'name' => 'Iran',
        'code' => 'IR',
        'phone_code' => '+98',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ir.svg',
        'locale' => 'fa_IR',
    ),
    array(
        'name' => 'Iraq',
        'code' => 'IQ',
        'phone_code' => '+964',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/iq.svg',
        'locale' => 'ar_IQ',
    ),
    array(
        'name' => 'Ireland',
        'code' => 'IE',
        'phone_code' => '+353',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ie.svg',
        'locale' => 'ga_IE',
    ),
    array(
        'name' => 'Israel',
        'code' => 'IL',
        'phone_code' => '+972',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/il.svg',
        'locale' => 'he_IL',
    ),
    array(
        'name' => 'Italy',
        'code' => 'IT',
        'phone_code' => '+39',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/it.svg',
        'locale' => 'it_IT',
    ),
    array(
        'name' => 'Jamaica',
        'code' => 'JM',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/jm.svg',
        'locale' => 'en_JM',
    ),
    array(
        'name' => 'Japan',
        'code' => 'JP',
        'phone_code' => '+81',
        'phoneLength' => '11',
        'flag' => 'assets/admin/img/flags/jp.svg',
        'locale' => 'ja_JP',
    ),
    array(
        'name' => 'Jordan',
        'code' => 'JO',
        'phone_code' => '+962',
        'phoneLength' =>
            array(
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/jo.svg',
        'locale' => 'ar_JO',
    ),
    array(
        'name' => 'Kazakhstan',
        'code' => 'KZ',
        'phone_code' => '+7',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/kz.svg',
        'locale' => 'kk_KZ',
    ),
    array(
        'name' => 'Kenya',
        'code' => 'KE',
        'phone_code' => '+254',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ke.svg',
        'locale' => 'en_KE',
    ),
    array(
        'name' => 'Kiribati',
        'code' => 'KI',
        'phone_code' => '+686',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ki.svg',
        'locale' => 'en_KI',
    ),
    array(
        'name' => 'Kosovo',
        'code' => 'XK',
        'phone_code' => '+383',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/xk.svg',
        'locale' => 'sq_XK',
    ),
    array(
        'name' => 'Kuwait',
        'code' => 'KW',
        'phone_code' => '+965',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/kw.svg',
        'locale' => 'ar_KW',
    ),
    array(
        'name' => 'Kyrgyzstan',
        'code' => 'KG',
        'phone_code' => '+996',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/kg.svg',
        'locale' => 'ky_KG',
    ),
    array(
        'name' => 'Laos',
        'code' => 'LA',
        'phone_code' => '+856',
        'phoneLength' =>
            array(
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/la.svg',
        'locale' => 'lo_LA',
    ),
    array(
        'name' => 'Latvia',
        'code' => 'LV',
        'phone_code' => '+371',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/lv.svg',
        'locale' => 'lv_LV',
    ),
    array(
        'name' => 'Lebanon',
        'code' => 'LB',
        'phone_code' => '+961',
        'phoneLength' =>
            array(
                7,
                8
            ),
        'flag' => 'assets/admin/img/flags/lb.svg',
        'locale' => 'ar_LB',
    ),
    array(
        'name' => 'Lesotho',
        'code' => 'LS',
        'phone_code' => '+266',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ls.svg',
        'locale' => 'en_LS',
    ),
    array(
        'name' => 'Liberia',
        'code' => 'LR',
        'phone_code' => '+231',
        'phoneLength' =>
            array(
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/lr.svg',
        'locale' => 'en_LR',
    ),
    array(
        'name' => 'Libya',
        'code' => 'LY',
        'phone_code' => '+218',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ly.svg',
        'locale' => 'ar_LY',
    ),
    array(
        'name' => 'Liechtenstein',
        'code' => 'LI',
        'phone_code' => '+423',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/li.svg',
        'locale' => 'de_LI',
    ),
    array(
        'name' => 'Lithuania',
        'code' => 'LT',
        'phone_code' => '+370',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/lt.svg',
        'locale' => 'lt_LT',
    ),
    array(
        'name' => 'Luxembourg',
        'code' => 'LU',
        'phone_code' => '+352',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/lu.svg',
        'locale' => 'fr_LU',
    ),
    array(
        'name' => 'Macau',
        'code' => 'MO',
        'phone_code' => '+853',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mo.svg',
        'locale' => 'zh_MO',
    ),
    array(
        'name' => 'Macedonia',
        'code' => 'MK',
        'phone_code' => '+389',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mk.svg',
        'locale' => 'mk_MK',
    ),
    array(
        'name' => 'Madagascar',
        'code' => 'MG',
        'phone_code' => '+261',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/mg.svg',
        'locale' => 'fr_MG',
    ),
    array(
        'name' => 'Malawi',
        'code' => 'MW',
        'phone_code' => '+265',
        'phoneLength' =>
            array(
                7,
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/mw.svg',
        'locale' => 'en_MW',
    ),
    array(
        'name' => 'Malaysia',
        'code' => 'MY',
        'phone_code' => '+60',
        'phoneLength' => '9 or 10',
        'flag' => 'assets/admin/img/flags/my.svg',
        'locale' => 'ms_MY',
    ),
    array(
        'name' => 'Maldives',
        'code' => 'MV',
        'phone_code' => '+960',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/mv.svg',
        'locale' => 'dv_MV',
    ),
    array(
        'name' => 'Mali',
        'code' => 'ML',
        'phone_code' => '+223',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ml.svg',
        'locale' => 'fr_ML',
    ),
    array(
        'name' => 'Malta',
        'code' => 'MT',
        'phone_code' => '+356',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mt.svg',
        'locale' => 'mt_MT',
    ),
    array(
        'name' => 'Marshall Islands',
        'code' => 'MH',
        'phone_code' => '+692',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/mh.svg',
        'locale' => 'en_MH',
    ),
    array(
        'name' => 'Martinique',
        'code' => 'MQ',
        'phone_code' => '+596',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/mq.svg',
        'locale' => 'fr_MQ',
    ),
    array(
        'name' => 'Mauritania',
        'code' => 'MR',
        'phone_code' => '+222',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mr.svg',
        'locale' => 'ar_MR',
    ),
    array(
        'name' => 'Mauritius',
        'code' => 'MU',
        'phone_code' => '+230',
        'phoneLength' => '7 or 8',
        'flag' => 'assets/admin/img/flags/mu.svg',
        'locale' => 'en_MU',
    ),
    array(
        'name' => 'Mayotte',
        'code' => 'YT',
        'phone_code' => '+262',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/yt.svg',
        'locale' => 'fr_YT',
    ),
    array(
        'name' => 'Mexico',
        'code' => 'MX',
        'phone_code' => '+52',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/mx.svg',
        'locale' => 'es_MX',
    ),
    array(
        'name' => 'Moldova',
        'code' => 'MD',
        'phone_code' => '+373',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/md.svg',
        'locale' => 'ro_MD',
    ),
    array(
        'name' => 'Monaco',
        'code' => 'MC',
        'phone_code' => '+377',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mc.svg',
        'locale' => 'fr_MC',
    ),
    array(
        'name' => 'Mongolia',
        'code' => 'MN',
        'phone_code' => '+976',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/mn.svg',
        'locale' => 'mn_MN',
    ),
    array(
        'name' => 'Montenegro',
        'code' => 'ME',
        'phone_code' => '+382',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/me.svg',
        'locale' => 'sr_ME',
    ),
    array(
        'name' => 'Montserrat',
        'code' => 'MS',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ms.svg',
        'locale' => 'en_MS',
    ),
    array(
        'name' => 'Morocco',
        'code' => 'MA',
        'phone_code' => '+212',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ma.svg',
        'locale' => 'ar_MA',
    ),
    array(
        'name' => 'Mozambique',
        'code' => 'MZ',
        'phone_code' => '+258',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/mz.svg',
        'locale' => 'pt_MZ',
    ),
    array(
        'name' => 'Namibia',
        'code' => 'NA',
        'phone_code' => '+264',
        'phoneLength' => '8 or 9',
        'flag' => 'assets/admin/img/flags/na.svg',
        'locale' => 'en_NA',
    ),
    array(
        'name' => 'Nauru',
        'code' => 'NR',
        'phone_code' => '+674',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/nr.svg',
        'locale' => 'en_NR',
    ),
    array(
        'name' => 'Nepal',
        'code' => 'NP',
        'phone_code' => '+977',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/np.svg',
        'locale' => 'ne_NP',
    ),
    array(
        'name' => 'Netherlands',
        'code' => 'NL',
        'phone_code' => '+31',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/nl.svg',
        'locale' => 'nl_NL',
    ),
    array(
        'name' => 'Netherlands Antilles',
        'code' => 'AN',
        'phone_code' => '+599',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/an.svg',
        'locale' => 'nl_AN',
    ),
    array(
        'name' => 'New Caledonia',
        'code' => 'NC',
        'phone_code' => '+687',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/nc.svg',
        'locale' => 'fr_NC',
    ),
    array(
        'name' => 'New Zealand',
        'code' => 'NZ',
        'phone_code' => '+64',
        'phoneLength' =>
            array(
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/nz.svg',
        'locale' => 'en_NZ',
    ),
    array(
        'name' => 'Nicaragua',
        'code' => 'NI',
        'phone_code' => '+505',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ni.svg',
        'locale' => 'es_NI',
    ),
    array(
        'name' => 'Niger',
        'code' => 'NE',
        'phone_code' => '+227',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/ne.svg',
        'locale' => 'fr_NE',
    ),
    array(
        'name' => 'Nigeria',
        'code' => 'NG',
        'phone_code' => '+234',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ng.svg',
        'locale' => 'en_NG',
    ),
    array(
        'name' => 'Niue',
        'code' => 'NU',
        'phone_code' => '+683',
        'phoneLength' => '4',
        'flag' => 'assets/admin/img/flags/nu.svg',
        'locale' => 'en_NU',
    ),
    array(
        'name' => 'Norfolk Island',
        'code' => 'NF',
        'phone_code' => '+672',
        'phoneLength' => '5',
        'flag' => 'assets/admin/img/flags/nf.svg',
        'locale' => 'en_NF',
    ),
    array(
        'name' => 'North Korea',
        'code' => 'KP',
        'phone_code' => '+850',
        'phoneLength' =>
            array(
                7,
                8
            ),
        'flag' => 'assets/admin/img/flags/kp.svg',
        'locale' => 'ko_KP',
    ),
    array(
        'name' => 'Northern Mariana Islands',
        'code' => 'MP',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/mp.svg',
        'locale' => 'en_MP',
    ),
    array(
        'name' => 'Norway',
        'code' => 'NO',
        'phone_code' => '+47',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/no.svg',
        'locale' => 'no_NO',
    ),
    array(
        'name' => 'Oman',
        'code' => 'OM',
        'phone_code' => '+968',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/om.svg',
        'locale' => 'ar_OM',
    ),
    array(
        'name' => 'Pakistan',
        'code' => 'PK',
        'phone_code' => '+92',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/pk.svg',
        'locale' => 'ur_PK',
    ),
    array(
        'name' => 'Palau',
        'code' => 'PW',
        'phone_code' => '+680',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/pw.svg',
        'locale' => 'en_PW',
    ),
    array(
        'name' => 'Palestine',
        'code' => 'PS',
        'phone_code' => '+970',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ps.svg',
        'locale' => 'ar_PS',
    ),
    array(
        'name' => 'Panama',
        'code' => 'PA',
        'phone_code' => '+507',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/pa.svg',
        'locale' => 'es_PA',
    ),
    array(
        'name' => 'Papua New Guinea',
        'code' => 'PG',
        'phone_code' => '+675',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/pg.svg',
        'locale' => 'en_PG',
    ),
    array(
        'name' => 'Paraguay',
        'code' => 'PY',
        'phone_code' => '+595',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/py.svg',
        'locale' => 'es_PY',
    ),
    array(
        'name' => 'Peru',
        'code' => 'PE',
        'phone_code' => '+51',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/pe.svg',
        'locale' => 'es_PE',
    ),
    array(
        'name' => 'Philippines',
        'code' => 'PH',
        'phone_code' => '+63',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ph.svg',
        'locale' => 'en_PH',
    ),
    array(
        'name' => 'Poland',
        'code' => 'PL',
        'phone_code' => '+48',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/pl.svg',
        'locale' => 'pl_PL',
    ),
    array(
        'name' => 'Portugal',
        'code' => 'PT',
        'phone_code' => '+351',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/pt.svg',
        'locale' => 'pt_PT',
    ),
    array(
        'name' => 'Puerto Rico',
        'code' => 'PR',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/pr.svg',
        'locale' => 'es_PR',
    ),
    array(
        'name' => 'Qatar',
        'code' => 'QA',
        'phone_code' => '+974',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/qa.svg',
        'locale' => 'ar_QA',
    ),
    array(
        'name' => 'Republic of the Congo',
        'code' => 'CG',
        'phone_code' => '+242',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/cg.svg',
        'locale' => 'fr_CG',
    ),
    array(
        'name' => 'Réunion',
        'code' => 'RE',
        'phone_code' => '+262',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/re.svg',
        'locale' => 'fr_RE',
    ),
    array(
        'name' => 'Romania',
        'code' => 'RO',
        'phone_code' => '+40',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ro.svg',
        'locale' => 'ro_RO',
    ),
    array(
        'name' => 'Russia',
        'code' => 'RU',
        'phone_code' => '+7',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ru.svg',
        'locale' => 'ru_RU',
    ),
    array(
        'name' => 'Rwanda',
        'code' => 'RW',
        'phone_code' => '+250',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/rw.svg',
        'locale' => 'rw_RW',
    ),
    array(
        'name' => 'Saint Barthélemy',
        'code' => 'BL',
        'phone_code' => '+590',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/bl.svg',
        'locale' => 'fr_BL',
    ),
    array(
        'name' => 'Saint Helena',
        'code' => 'SH',
        'phone_code' => '+290',
        'phoneLength' => '4',
        'flag' => 'assets/admin/img/flags/sh.svg',
        'locale' => 'en_SH',
    ),
    array(
        'name' => 'Saint Kitts and Nevis',
        'code' => 'KN',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/kn.svg',
        'locale' => 'en_KN',
    ),
    array(
        'name' => 'Saint Martin',
        'code' => 'MF',
        'phone_code' => '+590',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/mf.svg',
        'locale' => 'fr_MP',
    ),
    array(
        'name' => 'St Pierre & Miquelon',
        'code' => 'PM',
        'phone_code' => '+508',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/pm.svg',
        'locale' => 'fr_PM',
    ),
    array(
        'name' => 'St Vincent & Grenadines',
        'code' => 'VC',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/vc.svg',
        'locale' => 'en_VC',
    ),
    array(
        'name' => 'Samoa',
        'code' => 'WS',
        'phone_code' => '+685',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/ws.svg',
        'locale' => 'en_WS',
    ),
    array(
        'name' => 'San Marino',
        'code' => 'SM',
        'phone_code' => '+378',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/sm.svg',
        'locale' => 'it_SM',
    ),
    array(
        'name' => 'São Tomé and Príncipe',
        'code' => 'ST',
        'phone_code' => '+239',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/st.svg',
        'locale' => 'pt_ST',
    ),
    array(
        'name' => 'Saudi Arabia',
        'code' => 'SA',
        'phone_code' => '+966',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/sa.svg',
        'locale' => 'ar_SA',
    ),
    array(
        'name' => 'Senegal',
        'code' => 'SN',
        'phone_code' => '+221',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/sn.svg',
        'locale' => 'fr_SN',
    ),
    array(
        'name' => 'Serbia',
        'code' => 'RS',
        'phone_code' => '+381',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/rs.svg',
        'locale' => 'sr_RS',
    ),
    array(
        'name' => 'Seychelles',
        'code' => 'SC',
        'phone_code' => '+248',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/sc.svg',
        'locale' => 'en_SC',
    ),
    array(
        'name' => 'Sierra Leone',
        'code' => 'SL',
        'phone_code' => '+232',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/sl.svg',
        'locale' => 'en_SL',
    ),
    array(
        'name' => 'Singapore',
        'code' => 'SG',
        'phone_code' => '+65',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/sg.svg',
        'locale' => 'en_SG',
    ),
    array(
        'name' => 'Slovakia',
        'code' => 'SK',
        'phone_code' => '+421',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/sk.svg',
        'locale' => 'sk_SK',
    ),
    array(
        'name' => 'Slovenia',
        'code' => 'SI',
        'phone_code' => '+386',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/si.svg',
        'locale' => 'sl_SI',
    ),
    array(
        'name' => 'Solomon Islands',
        'code' => 'SB',
        'phone_code' => '+677',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/sb.svg',
        'locale' => 'en_SB',
    ),
    array(
        'name' => 'Somalia',
        'code' => 'SO',
        'phone_code' => '+252',
        'phoneLength' =>
            array(
                8,
                9
            ),
        'flag' => 'assets/admin/img/flags/so.svg',
        'locale' => 'so_SO',
    ),
    array(
        'name' => 'South Africa',
        'code' => 'ZA',
        'phone_code' => '+27',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/za.svg',
        'locale' => 'en_ZA',
    ),
    array(
        'name' => 'South Korea',
        'code' => 'KR',
        'phone_code' => '+82',
        'phoneLength' =>
            array(
                4,
                6,
                7,
                13
            ),
        'flag' => 'assets/admin/img/flags/kr.svg',
        'locale' => 'ko_KR',
    ),
    array(
        'name' => 'Spain',
        'code' => 'ES',
        'phone_code' => '+34',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/es.svg',
        'locale' => 'es_ES',
    ),
    array(
        'name' => 'Sri Lanka',
        'code' => 'LK',
        'phone_code' => '+94',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/lk.svg',
        'locale' => 'si_LK',
    ),
    array(
        'name' => 'St. Lucia',
        'code' => 'LC',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/lc.svg',
        'locale' => 'en_LC',
    ),
    array(
        'name' => 'Sudan',
        'code' => 'SD',
        'phone_code' => '+249',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/sd.svg',
        'locale' => 'ar_SD',
    ),
    array(
        'name' => 'Suriname',
        'code' => 'SR',
        'phone_code' => '+597',
        'phoneLength' =>
            array(
                6,
                7
            ),
        'flag' => 'assets/admin/img/flags/sr.svg',
        'locale' => 'nl_SR',
    ),
    array(
        'name' => 'Swaziland',
        'code' => 'SZ',
        'phone_code' => '+268',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/sr.svg',
        'locale' => 'en_SZ',
    ),
    array(
        'name' => 'Sweden',
        'code' => 'SE',
        'phone_code' => '+46',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/se.svg',
        'locale' => 'sv_SE',
    ),
    array(
        'name' => 'Switzerland',
        'code' => 'CH',
        'phone_code' => '+41',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ch.svg',
        'locale' => 'de_CH',
    ),
    array(
        'name' => 'Syria',
        'code' => 'SY',
        'phone_code' => '+963',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/sy.svg',
        'locale' => 'ar_SY',
    ),
    array(
        'name' => 'Taiwan',
        'code' => 'TW',
        'phone_code' => '+886',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/tw.svg',
        'locale' => 'zh_TW',
    ),
    array(
        'name' => 'Tajikistan',
        'code' => 'TJ',
        'phone_code' => '+992',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/tj.svg',
        'locale' => 'tg_TJ',
    ),
    array(
        'name' => 'Tanzania',
        'code' => 'TZ',
        'phone_code' => '+255',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/tz.svg',
        'locale' => 'sw_TZ',
    ),
    array(
        'name' => 'Thailand',
        'code' => 'TH',
        'phone_code' => '+66',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/th.svg',
        'locale' => 'th_TH',
    ),
    array(
        'name' => 'The Bahamas',
        'code' => 'BS',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/bs.svg',
        'locale' => 'en_BS',
    ),
    array(
        'name' => 'The Gambia',
        'code' => 'GM',
        'phone_code' => '+220',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/gm.svg',
        'locale' => 'en_GM',
    ),
    array(
        'name' => 'Timor-Leste',
        'code' => 'TL',
        'phone_code' => '+670',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/tl.svg',
        'locale' => 'tet_TL',
    ),
    array(
        'name' => 'Togo',
        'code' => 'TG',
        'phone_code' => '+228',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/tg.svg',
        'locale' => 'fr_TG',
    ),
    array(
        'name' => 'Tokelau',
        'code' => 'TK',
        'phone_code' => '+690',
        'phoneLength' => '4',
        'flag' => 'assets/admin/img/flags/tk.svg',
        'locale' => 'en_TK',
    ),
    array(
        'name' => 'Tonga',
        'code' => 'TO',
        'phone_code' => '+676',
        'phoneLength' => '5',
        'flag' => 'assets/admin/img/flags/to.svg',
        'locale' => 'en_TO',
    ),
    array(
        'name' => 'Trinidad and Tobago',
        'code' => 'TT',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/tt.svg',
        'locale' => 'en_TT',
    ),
    array(
        'name' => 'Tunisia',
        'code' => 'TN',
        'phone_code' => '+216',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/tn.svg',
        'locale' => 'ar_TN',
    ),
    array(
        'name' => 'Turkey',
        'code' => 'TR',
        'phone_code' => '+90',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/tr.svg',
        'locale' => 'tr_TR',
    ),
    array(
        'name' => 'Turkmenistan',
        'code' => 'TM',
        'phone_code' => '+993',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/tm.svg',
        'locale' => 'tk_TM',
    ),
    array(
        'name' => 'Turks and Caicos Islands',
        'code' => 'TC',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/tc.svg',
        'locale' => 'en_TC',
    ),
    array(
        'name' => 'Tuvalu',
        'code' => 'TV',
        'phone_code' => '+688',
        'phoneLength' => '5',
        'flag' => 'assets/admin/img/flags/tv.svg',
        'locale' => 'en_TV',
    ),
    array(
        'name' => 'Uganda',
        'code' => 'UG',
        'phone_code' => '+256',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ug.svg',
        'locale' => 'en_UG',
    ),
    array(
        'name' => 'Ukraine',
        'code' => 'UA',
        'phone_code' => '+380',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/uv.svg',
        'locale' => 'uk_UA',
    ),
    array(
        'name' => 'United Arab Emirates',
        'code' => 'AE',
        'phone_code' => '+971',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ae.svg',
        'locale' => 'ar_AE',
    ),
    array(
        'name' => 'United Kingdom',
        'code' => 'GB',
        'phone_code' => '+44',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/gb.svg',
        'locale' => 'en_GB',
    ),
    array(
        'name' => 'United States',
        'code' => 'US',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/us.svg',
        'locale' => 'en_US',
    ),
    array(
        'name' => 'Uruguay',
        'code' => 'UY',
        'phone_code' => '+598',
        'phoneLength' => '8',
        'flag' => 'assets/admin/img/flags/uy.svg',
        'locale' => 'es_UY',
    ),
    array(
        'name' => 'US Virgin Islands',
        'code' => 'VI',
        'phone_code' => '+1',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/vi.svg',
        'locale' => 'en_VI',
    ),
    array(
        'name' => 'Uzbekistan',
        'code' => 'UZ',
        'phone_code' => '+998',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/uz.svg',
        'locale' => 'uz_UZ',
    ),
    array(
        'name' => 'Vanuatu',
        'code' => 'VU',
        'phone_code' => '+678',
        'phoneLength' => '7',
        'flag' => 'assets/admin/img/flags/uv.svg',
        'locale' => 'bi_VU',
    ),
    array(
        'name' => 'Vatican City',
        'code' => 'VA',
        'phone_code' => '+39',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/va.svg',
        'locale' => 'it_VA',
    ),
    array(
        'name' => 'Venezuela',
        'code' => 'VE',
        'phone_code' => '+58',
        'phoneLength' => '10',
        'flag' => 'assets/admin/img/flags/ve.svg',
        'locale' => 'es_VE',
    ),
    array(
        'name' => 'Vietnam',
        'code' => 'VN',
        'phone_code' => '+84',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/vn.svg',
        'locale' => 'vi_VN',
    ),
    array(
        'name' => 'Wallis and Futuna',
        'code' => 'WF',
        'phone_code' => '+681',
        'phoneLength' => '6',
        'flag' => 'assets/admin/img/flags/wf.svg',
        'locale' => 'fr_WF',
    ),
    array(
        'name' => 'Yemen',
        'code' => 'YE',
        'phone_code' => '+967',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/ye.svg',
        'locale' => 'ar_YE',
    ),
    array(
        'name' => 'Zambia',
        'code' => 'ZM',
        'phone_code' => '+260',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/zm.svg',
        'locale' => 'en_ZM',
    ),
    array(
        'name' => 'Zimbabwe',
        'code' => 'ZW',
        'phone_code' => '+263',
        'phoneLength' => '9',
        'flag' => 'assets/admin/img/flags/zw.svg',
        'locale' => 'en_ZW',
    ),
);
