<?php
return [
  "Quick Links",
  "Read more",
  "Submit",
  "Filter",
  "Purchase now",
  "Explore Services",
  "Update",
  "Copy Link",
  "Add Item",
  "Company Policy",
  "Contact Us",
  "more about",
  "About us",
  "home",
  "Destination List",
  "Explore Top Destination",
  "Search Box",
  "Filter by Price",
  "Tour Type",
  "Duration",
  "Rating",
  "Filter Now",
  "phone",
  "email",
  "contact",
  "View All Tour",
  "Explore now",
  "view all offer",
  "destination",
  "package",
  "Contact Information",
  "your name",
  "your message",
  "your email address",
  "Discover",
  "Discover now",
  "Where to?",
  "When?",
  "Subscribe",
  "Enter Your Email",
  "Book Now",
  "save changes",
  "reset",
  "cancel",
  "password",
  "Current Password",
  "new password",
  "Add Fund",
  "fund",
  "amount",
  "success",
  "requested",
  "pending",
  "si no",
  "image",
  "title",
  "paid",
  "submit",
  "Charge",
  "Enable Two Factor Authenticatior",
  "Download app",
  "Tour type",
  "departure time",
  "date",
  "Booking Submission",
  "First Name",
  "Last Name",
  "Address Line",
  "Postal code",
  "ZIP code",
  "Province",
  "Region",
  "City",
  "Coupon code",
  "Number of Infant",
  "Number of Children",
  "Update Date",
  "Departure date",
  "Your booking",
  "How would you like to pay",
  "Message",
  "Select Currency",
  "Payment Method",
  "Gross Total",
  "Discount",
  "Apply",
  "Admin",
  "Keep Updated With Our Recent Blog",
  "Popular  Destination In Your Locations Here",
  "reviews",
  "Starting From",
  "Share",
  "Site Admin",
  "Learn more",
  "Blog List is empty here",
  "Recent post",
  "Find  Most",
  "Tour of The World",
  "Inspired",
  "Experience the Incredible Journey With nextDestina",
  "Destination List is empty here",
  "Popular  Packages In Your",
  "Here",
  "Locations",
  "package List is empty here",
  "Details Info",
  "Days",
  "Meeting And Pickup",
  "Time saved to wishlist",
  "Proceed Booking",
  "Below 3 Years",
  "Below 12 Years",
  "Over 12 Years",
  "Infant",
  "Children",
  "infant",
  "children",
  "adult",
  "Adult",
  "Booking Form",
  "Start From",
  "Search",
  "Search here",
  "Reviews",
  "Add your reviews",
  "Submit Review",
  "Write your comments",
  "Accept",
  "Close",
  "Sign In",
  "Sign Up",
  "dashboard",
  "Next Destina",
  "All Rights Reserved",
  "copyright",
  "Verification Center",
  "Sign Out",
  "logout",
  "Notification Permission",
  "Need Help?",
  "2FA Verification",
  "My Profile",
  "You have no notifications",
  "new notifications",
  "Transaction",
  "Support Ticket",
  "Tour History",
  "Fund History",
  "Add fund",
  "Funds",
  "KYC",
  "Notifications",
  "Account",
  "compared to others",
  "Advantages",
  "What are our",
  "There are many choices of interesting places to make a story in your journey",
  "Successful Years",
  "Submit Now",
  "Select to subscribe to our newsletter and update and we will send you all updates about",
  "Write your message",
  "Subject",
  "Phone Number",
  "Your Email",
  "Your Name",
  "Customer",
  "Travel",
  "Best Travel Site Travels",
  "Lets Explore the World",
  "Get Every Tour & Package Updates",
  "Embark on",
  "Unknown Locations",
  "Adventures",
  "Explore the globe with",
  "Feb24",
  "Tours",
  "Stay Updated With Our",
  "By",
  "From Date",
  "To Date",
  "Rejected",
  "Requested",
  "Success",
  "status",
  "Enter Amount",
  "You will pay in currency",
  "Fund details",
  "How would you like to deposit",
  "Fund List is empty here",
  "Time & Date",
  "Amount In Base Currency",
  "Transaction ID",
  "Fund history",
  "KYC Verification",
  "action",
  "Submitted At",
  "type",
  "SL",
  "Favourite List is empty here",
  "Favourite List",
  "Added At",
  "Sl No",
  "Total Person",
  "Booking Date",
  "Number Of Infant",
  "Number Of Children",
  "Number Of Adults",
  "Total Amount",
  "Package Name",
  "Date To",
  "Date From",
  "Package Title",
  "My Wallet",
  "Total Support Ticket",
  "All Time",
  "Total Transaction",
  "Total Booked Tour",
  "Enter the name on your card",
  "Enter your card number",
  "Your Card Information",
  "PAY NOW",
  "CVC CODE",
  "EXPIRATION DATE",
  "CARD NUMBER",
  "Please Pay",
  "To Get",
  "Pay Now",
  "TO",
  "SCAN TO SEND",
  "PLEASE SEND EXACTLY",
  "Payment Preview",
  "Confirm Now",
  "Please pay",
  "You have requested to deposit",
  "Please follow the instruction below",
  "Pay with VoguePay",
  "Verify your process instantly",
  "KYC Information",
  "Identity Verification",
  "Notification",
  "Password",
  "Profile",
  "sms",
  "browser",
  "We need permission from your browser to show notifications.",
  "Request Permission",
  "Save Changes",
  "Confirm Password",
  "New Password",
  "state",
  "country",
  "language",
  "About Me",
  "address",
  "phone number",
  "last name",
  "Allowed JPG, GIF or PNG. Max size of 4Mb",
  "Upload New Photo",
  "Profile Details",
  "Enter Subject",
  "Support Ticket Create",
  "File",
  "Ticket List is empty here",
  "Serial",
  "Created At",
  "Last Reply",
  "Are you want to close ticket",
  "Confirmation",
  "Closed",
  "Customer Reply",
  "Answered",
  "Open",
  "admin",
  "Support Ticket View",
  "Tour History is empty here",
  "Accepted",
  "Product Filter",
  "Transaction Id",
  "Transaction List is empty here!",
  "Gateway",
  "Verify",
  "Enter Your Password",
  "Verify Your OTP",
  "Verify Your OTP to Disable",
  "DOWNLOAD APP",
  "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
  "Use Google Authenticator to Scan the QR code  or use the code",
  "Google Authenticator",
  "Enable Two Factor Authenticator",
  "Two Factor Authenticator",
  "Disable Two Factor Authenticator",
  "2 Step Security",
  "Please confirm your password before continuing",
  "Send Password Reset Link",
  "Email Address",
  "Reset Password",
  "Your Email Address is",
  "Your Mobile Number is",
  "Create an account",
  "Do not have an account",
  "Github",
  "facebook",
  "Google",
  "Forgot password",
  "Welcome back",
  "Hey Enter your details to get sign in to your account",
  "signup",
  "Login Here",
  "click here to request another",
  "If you did not receive the email",
  "Before proceeding, please check your email for a verification link",
  "A fresh verification link has been sent to your email address",
  "Categories",
  "In today is fast-paced world, managing bill payments can become a tedious and time-consuming task. Fortunately, with the advent of online payment services.",
  "Latest Blogs & Articles",
  "No",
  "Yes",
  "package List is empty here!",
  "from",
  "In today's fast-paced world, managing bill payments can become a tedious and time-consuming task. Fortunately, with the advent of online payment services.",
  "Discover the world’s best travel agency for making your adventure great with us",
  "Price :",
  "Account Settings",
  "Paid Amount",
  "SI No",
  "SL.",
  "SI",
  "Transaction History",
  "How would you like to deposit?",
  "Support Ticket List",
  "All status",
  "Create Ticket",
  "Transactions",
  "profile",
  "Recent Devices",
  "Verify your process instantly.",
  "Kyc Type",
  "Select Kyc Type",
  "Full Name",
  "Price" ,
  "Clear all notification",
  "You have",
  "See more",
  "e.g. Dubai",
  "Useful Link",
  "Call Us:",
  "Enter your email",
  "Moments",
  "Discover The",
  "Card Acceptance",
  "We Accept all major Credit & Debit Cards",
  "zip code",
  "app",
  "Payable Amount",
  "Welcome back!",
  "Don't have an account?",
  "Remember me",
  "Username",
  "Username",
  "Create Account",
  "Creative Account",
  "Booking Information",
  "Package Title: ",
  "Date: ",
  "Start Price: ",
  "Total Infants: ",
  "Total Children: ",
  "Total Adults: ",
  "status: ",
  "Transaction ID: ",
  "Total Price: ",
  "Total Persons: ",
  "Select Date"
];
